### PR TITLE
Make editor page look better

### LINKED ISSUE #40: Make editor look prettier

### PR DESCRIPTION
**Pull request by 20jasper**
Mrge #39 before this

Closes #40 

# Description

I mad it look good 👍👍👍👍

## Testing

It works

## Type of change

Please remove all except for everything applicable, and then remove this line.

- Bug fix (non-breaking change which fixes an issue)

## Screenshots

100 Editors text area

### CODE REVIEW

**Review by windyScripts — DISMISSED** [review]
Looks great. Given time constraints, I don't consider the formatting related issues blocking, nice job!

**Comment by nmpereira** [comment]
Looks like the webrtc sharing is broken on this PR. It seems to be working on the main deployment and locally. Will debug and report.

**Comment by nmpereira** [comment]
Looks like the editor css is a little broken

image

**Comment by nmpereira** [comment]
@20jasper Can you also add functionality where the cursor gets focused on the text editor when user joins the room

**Review by Katherine29a — APPROVED** [review]

**Pull request merged**
